# Generated by Django 5.2.12 on 2026-03-05 22:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('women_wedding', 'Women Wedding'), ('graduation', 'Graduation'), ('men_wedding', 'Men Wedding'), ('newborn', 'New Born'), ('opening', 'Opening'), ('birthday', 'Birthday')], max_length=20)),
                ('location_text', models.CharField(blank=True, max_length=300)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('card_text_name', models.CharField(blank=True, max_length=200)),
                ('card_text_date', models.CharField(blank=True, max_length=100)),
                ('card_text_location', models.CharField(blank=True, max_length=300)),
                ('card_text_welcome', models.CharField(blank=True, max_length=500)),
                ('message_language', models.CharField(choices=[('ar', 'Arabic'), ('en', 'English')], default='ar', max_length=2)),
                ('include_qr', models.BooleanField(default=True)),
                ('delivery_method', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS')], default='whatsapp', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('payment_pending', 'Payment Pending'), ('active', 'Active'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('total_price_sar', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'events_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventDesign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('women_wedding', 'Women Wedding'), ('graduation', 'Graduation'), ('men_wedding', 'Men Wedding'), ('newborn', 'New Born'), ('opening', 'Opening'), ('birthday', 'Birthday')], max_length=20)),
                ('name_ar', models.CharField(blank=True, max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100)),
                ('design_image', models.ImageField(blank=True, null=True, upload_to='designs/')),
                ('is_premade', models.BooleanField(default=True)),
                ('text_positions', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'events_eventdesign',
            },
        ),
        migrations.CreateModel(
            name='Invitee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('invite_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('message_sent', models.BooleanField(default=False)),
                ('response_status', models.CharField(choices=[('waiting', 'Waiting'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='waiting', max_length=10)),
                ('arrived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'events_invitee',
                'ordering': ['name'],
            },
        ),
    ]
